import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Copy, Check, Shield, Globe, MapPin, Zap, Info, Flag, Building, Navigation, Share2, Eye, X, Activity, Server, Cpu } from 'lucide-react';
import { useState } from 'react';
import type { IpApiResponse as IpData } from '@/types';

const DetailItem = ({ label, value, icon: Icon, fullWidth = false, greenValue = true }: { label: string; value: string | number | boolean; icon: any; fullWidth?: boolean; greenValue?: boolean }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (value === undefined || value === null || typeof value === 'boolean') return;
    navigator.clipboard.writeText(String(value));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const isBool = typeof value === 'boolean';
  const displayValue = isBool ? (value ? 'DETECTED' : 'CLEAN') : (value || 'N/A');

  return (
    <div className={`flex items-center justify-between group py-1.5 border-b border-white/5 last:border-0 ${fullWidth ? 'col-span-full' : ''}`}>
      <div className="flex items-center gap-3 overflow-hidden">
        <div className="p-1.5 rounded bg-white/5 text-white/30 group-hover:text-primary transition-colors">
          <Icon size={12} />
        </div>
        <div className="overflow-hidden">
          <p className="text-[8px] text-white/40 uppercase tracking-widest leading-none mb-1">{label}</p>
          <p className={`text-[11px] font-bold leading-tight ${greenValue && !isBool ? 'text-primary' : isBool && value ? 'text-red-500' : 'text-white/90'}`}>
            {displayValue}
          </p>
        </div>
      </div>
      {!isBool && value && (
        <button
          onClick={handleCopy}
          className="p-1.5 hover:bg-white/10 rounded text-white/20 hover:text-primary transition-all active:scale-90 flex-shrink-0 ml-2"
        >
          {copied ? <Check size={12} className="text-primary" /> : <Copy size={12} />}
        </button>
      )}
    </div>
  );
};

const IpDetailsCard: React.FC<{ data: IpData }> = ({ data }) => {
  const [showModal, setShowModal] = useState(false);
  const [allCopied, setAllCopied] = useState(false);

  const restCountry = data.countryDetails;
  const flagUrl = restCountry?.flags?.png || restCountry?.flags?.svg || '';
  const fullAddress = data.addressDetails?.display_name;

  const copyAll = () => {
    const report = `
╔════════════════════════════════════════════════════════════╗
║          SIGNAL INTELLIGENCE REPORT - TOP SECRET           ║
╚════════════════════════════════════════════════════════════╝

[ TARGET IDENTIFICATION ]
IP Address  : ${data.query}
Node Status : ACTIVE / SECURE

[ NETWORK VECTOR ]
ISP         : ${data.isp}
Org         : ${data.org}
ASN Gateway : ${data.as}

[ GEOSPATIAL DATA ]
Location    : ${data.city}, ${data.regionName}, ${data.country}
Coordinates : ${data.lat}, ${data.lon}
Postal ID   : ${data.zip}
Full Address: ${fullAddress || 'N/A'}

[ SOVEREIGN INTEL ]
Country     : ${restCountry?.name?.common || data.country}
Capital     : ${restCountry?.capital?.[0] || 'N/A'}
Population  : ${restCountry?.population?.toLocaleString() || 'N/A'}
Currency    : ${Object.keys(restCountry?.currencies || {}).join(', ') || 'N/A'}

[ SECURITY PROFILE ]
Proxy/VPN   : ${data.proxy ? 'DETECTED' : 'CLEAN'}
DataCenter  : ${data.hosting ? 'YES' : 'NO'}
Mobile Net  : ${data.mobile ? 'YES' : 'NO'}

--------------------------------------------------------------
REPORT GENERATED BY NEXUS SHADOW PROTOCOL // 2026
--------------------------------------------------------------
    `.trim();

    navigator.clipboard.writeText(report);
    setAllCopied(true);
    setTimeout(() => setAllCopied(false), 2000);
  };

  return (
    <>
      <Card className="glass-card border-white/10 overflow-hidden h-full flex flex-col shadow-2xl relative">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-primary/50 to-transparent" />

        <CardHeader className="pb-1 py-4 px-5 border-b border-white/5 flex flex-row items-center justify-between bg-white/[0.02]">
          <div className="flex items-center gap-4">
            {flagUrl && (
              <div className="relative">
                <img
                  src={flagUrl}
                  alt={data.country}
                  className="w-8 h-5 object-cover rounded-sm border border-white/10"
                />
                <div className="absolute inset-0 shadow-[inset_0_0_8px_rgba(0,0,0,0.5)]" />
              </div>
            )}
            <CardTitle className="text-[11px] font-black tracking-[0.2em] uppercase text-white/60 flex items-center gap-2">
              <Shield size={14} className="text-primary" />
              SIGNAL_INTELLIGENCE
            </CardTitle>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowModal(true)}
              className="p-2 hover:bg-white/10 rounded-full text-white/30 hover:text-primary transition-all hover:scale-110"
              title="Expand Intelligence"
            >
              <Eye size={16} />
            </button>
            <button
              onClick={copyAll}
              className="p-2 hover:bg-white/10 rounded-full text-white/30 hover:text-primary transition-all hover:scale-110"
              title="Copy Signal Data"
            >
              {allCopied ? <Check size={16} className="text-primary" /> : <Share2 size={16} />}
            </button>
          </div>
        </CardHeader>

        <CardContent className="p-5 pt-3 flex-1 overflow-y-auto custom-scrollbar space-y-6">
          <section className="animate-in slide-in-from-left duration-500">
            <h4 className="text-[8px] text-white/20 font-black tracking-[0.4em] uppercase mb-3 flex items-center gap-2">
              <Activity size={10} className="text-primary" /> NETWORK_ANALYSIS
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6">
              <DetailItem label="Source IP" value={data.query} icon={Globe} />
              <DetailItem label="ISP Provider" value={data.isp} icon={Zap} />
              <DetailItem label="Org / Entity" value={data.org} icon={Building} />
              <DetailItem label="Route ASN" value={data.as} icon={Navigation} />
            </div>
          </section>

          <section className="animate-in slide-in-from-left duration-700">
            <h4 className="text-[8px] text-white/20 font-black tracking-[0.4em] uppercase mb-3 flex items-center gap-2">
              <MapPin size={10} className="text-primary" /> GEOSPATIAL_DATAPOINT
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6">
              <DetailItem label="Latitude" value={data.lat} icon={Navigation} />
              <DetailItem label="Longitude" value={data.lon} icon={Navigation} />
              <DetailItem label="Node City" value={data.city} icon={MapPin} />
              <DetailItem label="Postal ID" value={data.zip} icon={MapPin} />
            </div>
          </section>

          <section className="grid grid-cols-3 gap-3 pt-2">
            <div className={`p-2.5 rounded-lg border border-white/5 bg-white/[0.02] text-center transition-all hover:bg-white/[0.04] ${data.proxy ? 'border-red-500/20' : 'border-primary/20'}`}>
              <p className="text-[7px] font-black text-white/20 uppercase mb-1">PROXY_SHIELD</p>
              <p className={`text-[10px] font-black ${data.proxy ? 'text-red-500' : 'text-primary'}`}>{data.proxy ? 'ACTIVE' : 'NONE'}</p>
            </div>
            <div className={`p-2.5 rounded-lg border border-white/5 bg-white/[0.02] text-center transition-all hover:bg-white/[0.04] ${data.hosting ? 'border-red-500/20' : 'border-primary/20'}`}>
              <p className="text-[7px] font-black text-white/20 uppercase mb-1">DC_HOSTING</p>
              <p className={`text-[10px] font-black ${data.hosting ? 'text-red-500' : 'text-primary'}`}>{data.hosting ? 'YES' : 'NO'}</p>
            </div>
            <div className="p-2.5 rounded-lg border border-white/5 bg-white/[0.02] text-center transition-all hover:bg-white/[0.04]">
              <p className="text-[7px] font-black text-white/20 uppercase mb-1">CELL_RADIO</p>
              <p className="text-[10px] font-black text-white/60">{data.mobile ? 'YES' : 'NO'}</p>
            </div>
          </section>
        </CardContent>
      </Card>

      {showModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-8">
          <div className="absolute inset-0 bg-black/90 backdrop-blur-xl animate-in fade-in duration-300" onClick={() => setShowModal(false)} />
          <div className="relative w-full max-w-5xl max-h-[90vh] glass-card border-white/20 rounded-xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-300 shadow-[0_0_100px_rgba(0,0,0,0.5)]">

            <div className="p-6 border-b border-white/10 flex justify-between items-center bg-white/[0.03]">
              <div className="flex items-center gap-4">
                <div className="w-10 h-10 rounded bg-primary/20 flex items-center justify-center border border-primary/40">
                  <Activity className="text-primary animate-pulse" size={24} />
                </div>
                <div>
                  <h3 className="text-sm font-black tracking-[0.5em] uppercase hacking-text">Full Trace Intelligence Report</h3>
                  <p className="text-[10px] text-white/30 uppercase tracking-widest mt-1">Classification: Top Secret // Node Identifier: {data.query}</p>
                </div>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="w-10 h-10 flex items-center justify-center hover:bg-white/10 rounded-full text-white/40 hover:text-white transition-all"
              >
                <X size={24} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto custom-scrollbar p-8 bg-black/40">
              <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

                <div className="space-y-8">
                  <div>
                    <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4 flex items-center gap-2">
                      <Server size={14} /> Network Infrastructure
                    </h5>
                    <div className="space-y-4">
                      <DetailItem label="Protocol IP" value={data.query} icon={Globe} />
                      <DetailItem label="Internet Service Provider" value={data.isp} icon={Zap} />
                      <DetailItem label="Registered Organization" value={data.org} icon={Building} />
                      <DetailItem label="BGP Autonomous System" value={data.as} icon={Navigation} />
                      <DetailItem label="Node Timezone" value={data.timezone} icon={Activity} />
                    </div>
                  </div>

                  <div>
                    <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4 flex items-center gap-2">
                      <Shield size={14} /> Security Profile
                    </h5>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="p-4 rounded-lg bg-white/[0.03] border border-white/5">
                        <p className="text-[8px] text-white/20 uppercase font-black mb-2">Proxy Detection</p>
                        <p className={`text-sm font-black ${data.proxy ? 'text-red-500' : 'text-primary'}`}>{data.proxy ? 'COMPROMISED' : 'SECURE'}</p>
                      </div>
                      <div className="p-4 rounded-lg bg-white/[0.03] border border-white/5">
                        <p className="text-[8px] text-white/20 uppercase font-black mb-2">Hosting Analysis</p>
                        <p className={`text-sm font-black ${data.hosting ? 'text-red-500' : 'text-primary'}`}>{data.hosting ? 'DATA_CENTER' : 'RESIDENTIAL'}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="space-y-8">
                  <div>
                    <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4 flex items-center gap-2">
                      <MapPin size={14} /> Physical Location
                    </h5>
                    <div className="space-y-4">
                      <DetailItem label="Country / Sovereign" value={data.country} icon={Flag} />
                      <DetailItem label="Region / Province" value={data.regionName} icon={MapPin} />
                      <DetailItem label="City / Local Node" value={data.city} icon={MapPin} />
                      <DetailItem label="Postal Identifier" value={data.zip} icon={MapPin} />
                      <DetailItem label="Precise Address" value={fullAddress || 'N/A'} icon={Info} fullWidth />
                    </div>
                  </div>

                  {restCountry && (
                    <div>
                      <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4 flex items-center gap-2">
                        <Flag size={14} /> Country Intelligence
                      </h5>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="p-3 rounded bg-white/[0.02] border border-white/5">
                          <p className="text-[7px] text-white/20 uppercase mb-1">Capital City</p>
                          <p className="text-xs font-bold">{restCountry.capital?.[0]}</p>
                        </div>
                        <div className="p-3 rounded bg-white/[0.02] border border-white/5">
                          <p className="text-[7px] text-white/20 uppercase mb-1">Currency</p>
                          <p className="text-xs font-bold">{Object.keys(restCountry.currencies || {}).join(', ')}</p>
                        </div>
                        <div className="p-3 rounded bg-white/[0.02] border border-white/5">
                          <p className="text-[7px] text-white/20 uppercase mb-1">Population</p>
                          <p className="text-xs font-bold">{restCountry.population?.toLocaleString()}</p>
                        </div>
                        <div className="p-3 rounded bg-white/[0.02] border border-white/5">
                          <p className="text-[7px] text-white/20 uppercase mb-1">Subregion</p>
                          <p className="text-xs font-bold">{restCountry.subregion}</p>
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                <div className="space-y-8">
                  <div>
                    <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4 flex items-center gap-2">
                      <Cpu size={14} /> Technical Metadata
                    </h5>
                    <div className="p-6 rounded-xl bg-black border border-white/10 relative overflow-hidden">
                      <div className="absolute top-0 right-0 p-2 opacity-10">
                        <Cpu size={40} />
                      </div>
                      <div className="space-y-4 relative z-10">
                        <div className="flex justify-between items-center border-b border-white/5 pb-2">
                          <span className="text-[9px] text-white/30 uppercase font-black">LATITUDE</span>
                          <span className="text-xs font-mono text-primary font-bold">{data.lat}</span>
                        </div>
                        <div className="flex justify-between items-center border-b border-white/5 pb-2">
                          <span className="text-[9px] text-white/30 uppercase font-black">LONGITUDE</span>
                          <span className="text-xs font-mono text-primary font-bold">{data.lon}</span>
                        </div>
                        <div className="flex justify-between items-center border-b border-white/5 pb-2">
                          <span className="text-[9px] text-white/30 uppercase font-black">STATUS_CODE</span>
                          <span className="text-xs font-mono text-green-500 font-bold">200 OK</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-[9px] text-white/30 uppercase font-black">TRACE_TYPE</span>
                          <span className="text-xs font-mono text-white/60 font-bold">{data.query?.startsWith('GRID') ? 'COORDINATE' : 'IP_PACKET'}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h5 className="text-[10px] font-black text-primary tracking-[0.2em] uppercase mb-4">Raw Signal Payload</h5>
                    <div className="p-4 rounded-lg bg-black border border-white/5 max-h-[200px] overflow-auto custom-scrollbar">
                      <pre className="text-[9px] font-mono text-white/20 leading-tight">
                        {JSON.stringify(data, null, 2)}
                      </pre>
                    </div>
                  </div>
                </div>

              </div>
            </div>

            <div className="p-6 border-t border-white/10 bg-white/[0.03] flex justify-between items-center">
              <div className="flex gap-4">
                <div className="flex items-center gap-2 text-[9px] text-white/30 font-black tracking-widest">
                  <div className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
                  DATA STREAM ENCRYPTED
                </div>
                <div className="flex items-center gap-2 text-[9px] text-white/30 font-black tracking-widest">
                  <div className="w-1.5 h-1.5 rounded-full bg-white/10" />
                  ISO/SEC 27001 COMPLIANT
                </div>
              </div>
              <button
                onClick={copyAll}
                className="px-8 py-3 bg-primary text-black text-[10px] font-black uppercase tracking-[0.3em] rounded hover:bg-primary/90 transition-all shadow-[0_0_30px_rgba(0,255,0,0.2)] active:scale-95"
              >
                {allCopied ? 'Intelligence Copied' : 'Copy Intelligence Report'}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default IpDetailsCard;
